name: Continuous deployment workflow (Node.js)

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure pages
        uses: actions/configure-pages@v2
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build artifacts
        run: npm run build
      - name: Generate 404.html (github pages)
        run: cp './dist/taco-visualizer/index.html' './dist/taco-visualizer/404.html'
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist/taco-visualizer/'
      - name: Deploy artifacts
        id: deployment
        uses: actions/deploy-pages@v1